添加S3云及华为OBS适配接口
storezhang/uoa pull request #2
Opened 2021-10-22 07:24 UTC by jiangchuan0426

2021-10-25 05:54 UTC, storezhang requested changes

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +	"context"
使用``

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +type _aws struct {
_s3

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +		return false, err
命名返回，不要使用return xx，直接return，保证返回的默认值是正确的

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +	return
return之前空行

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +	return
return之前空行

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +	val, errGet := credential.Get()
为什么不复用err

2021-10-25 05:54 UTC, storezhang commented on aws.go
> +	return
return之前换行

2021-10-25 05:54 UTC, storezhang commented on cos.go
> +	"context"
``

2021-10-25 05:54 UTC, storezhang commented on delete_option.go
> +		bucket string // 桶名称，非必填参数，针对S3需传入
// 桶名称，非必填参数，针对S3需传入
bucket string

2021-10-29 01:47 UTC, jiangchuan0426 commented on aws.go
> +	"context"
已修改

2021-10-29 01:48 UTC, jiangchuan0426 commented on aws.go
> +type _aws struct {
已修改

2021-10-29 01:48 UTC, jiangchuan0426 commented on aws.go
> +		return false, err
已修改

2021-10-29 01:48 UTC, jiangchuan0426 commented on aws.go
> +	return
已修改

2021-10-29 01:48 UTC, jiangchuan0426 commented on aws.go
> +	return
已修改

2021-10-29 01:49 UTC, jiangchuan0426 commented on aws.go
> +	val, errGet := credential.Get()
已修改

2021-10-29 01:49 UTC, jiangchuan0426 commented on aws.go
> +	return
已修改

2021-10-29 01:49 UTC, jiangchuan0426 commented on delete_option.go
> +		bucket string // 桶名称，非必填参数，针对S3需传入
已修改

2022-09-02 11:53 UTC, closed without merging